[package]
name = "rumqttd"
description = "Distributed, embeddable mqtt broker library"
license = "Apache-2.0"
version = "0.4.0"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2018"
keywords = ["mqtt", "broker", "iot", "kafka", "nats"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "librumqttd"
path = "src/lib.rs"

[[bin]]
name = "rumqttd"
path = "src/bin.rs"

[dependencies]
rumqttlog = { path = "../rumqttlog", version = "0.5"}
mqttbytes = { path = "../mqttbytes", version = "0.2" }
tokio = { version = "1.0", features = ["full"] }
tokio-rustls = "0.22"
tokio-compat-02 = "0.2"
serde = { version = "1", features = ["derive"] }
log = "0.4"
thiserror = "1"
argh = "0.1.3"
confy = "0.4.0"
pretty_env_logger = "0.4"
bytes = "1.0"
prost = "0.6"
warp = "0.2"
pprof = { version = "0.3", features = ["flamegraph", "protobuf"] }
ctrlc = "=3.1"
futures-util = "0.3.8"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3"
