[package]
name = "rumqttd"
version = "0.12.0-beta.2"
license = "Apache-2.0"
description = "rumqttd is a high performance MQTT broker written in Rust which is light weight and embeddable"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2021"
keywords = ["mqtt", "broker", "iot", "kafka", "nats"]
categories = ["network-programming"]
repository = "https://github.com/bytebeamio/rumqtt/"

[dependencies]
tokio = { version = "1.4.0", features = ["rt", "time", "net", "io-util", "macros"]}
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.66"
bytes = { version = "1", features = ["serde"] }
flume = "0.10.9"
slab = "0.4.3"
thiserror = "1.0.24"
tokio-util = { version = "0.7", features = ["codec"], optional = true }
tokio-rustls =  { version = "0.23.0", optional = true }
tokio-native-tls = { version = "0.3", optional = true }
rustls-pemfile = { version = "0.3.0", optional = true }
tokio-tungstenite = { version = "0.15.0", optional = true }
websocket-codec = { version = "0.5.1", optional = true }
rouille = "3.1.1"
x509-parser = {version= "0.9.2", optional = true}
futures-util = { version = "0.3.16", optional = true}
parking_lot = "0.11.2"
config = "0.13"
structopt = "0.3.26"
tracing = { version="0.1", features=["log"] }
tracing-subscriber = { version="0.3.16", features=["env-filter"] }
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"

[features]
default = ["use-rustls"]
use-rustls = ["tokio-rustls", "rustls-pemfile", "x509-parser"]
use-native-tls = ["tokio-native-tls" , "x509-parser"]
websockets = ["tokio-tungstenite", "websocket-codec", "tokio-util", "futures-util"]
validate-tenant-prefix = []

[dev-dependencies]
tokio = { version = "1.4.0", features = ["rt", "time", "net", "io-util", "macros", "sync"]}
pretty_env_logger = "0.4.0"
config = "0.13"
pretty_assertions = "1.3.0"

[target.'cfg(not(any(target_env = "msvc", target_env = "musl")))'.dependencies]
jemallocator = "0.3"

[build-dependencies]
vergen = "7.4.2"
