[package]
name = "rumqttd"
version = "0.16.0"
license = "Apache-2.0"
description = "rumqttd is a high performance MQTT broker written in Rust which is light weight and embeddable"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2021"
keywords = ["mqtt", "broker", "iot", "kafka", "nats"]
categories = ["network-programming"]
repository = "https://github.com/bytebeamio/rumqtt/"

[dependencies]
tokio = { version = "1.0", features = ["rt", "time", "net", "io-util", "macros"]}
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.66"
bytes = { version = "1", features = ["serde"] }
flume = { version = "0.10.9", default-features = false, features = ["async"]}
slab = "0.4.3"
thiserror = "1.0.24"
tokio-util = { version = "0.7", features = ["codec"], optional = true }
tokio-rustls = { version = "0.24", optional = true }
rustls-webpki = { version = "0.101.1", optional = true }
tokio-native-tls = { version = "0.3", optional = true }
rustls-pemfile = { version = "1", optional = true }
async-tungstenite = { version = "0.22.2", default-features = false, features = ["tokio-runtime"], optional = true }
ws_stream_tungstenite = { version = "0.10.0", default-features = false, features = ["tokio_io"], optional = true }
x509-parser = {version= "0.15.0", optional = true}
futures-util = { version = "0.3.16", optional = true}
parking_lot = "0.12.1"
config = "0.13"
tracing = { version="0.1", features=["log"] }
tracing-subscriber = { version="0.3.16", features=["env-filter"] }
metrics = "0.21.1"
metrics-exporter-prometheus = "0.12.1"
clap = { version = "4.2", features = ["derive"] }
axum = "0.6.4"
rand = "0.8.5"

[features]
default = ["use-rustls"]
use-rustls = ["dep:tokio-rustls", "dep:rustls-webpki", "dep:rustls-pemfile", "dep:x509-parser"]
use-native-tls = ["dep:tokio-native-tls", "dep:x509-parser"]
websocket = ["dep:async-tungstenite", "dep:tokio-util", "dep:futures-util", "dep:ws_stream_tungstenite"]
websockets = ["websocket"]
validate-tenant-prefix = []
allow-duplicate-clientid = []

[dev-dependencies]
pretty_env_logger = "0.5.0"
config = "0.13"
pretty_assertions = "1.4.0"
