[package]
name = "rumqttd"
description = "Distributed, embeddable mqtt broker library"
license = "Apache-2.0"
version = "0.0.1"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "librumqttd"
path = "src/lib.rs"

[[bin]]
name = "rumqttd"
path = "src/bin.rs"

[dependencies]
rumqttlog = { path = "../rumqttlog", version = "0.1"}
rumqttc = { path = "../rumqttc", version = "0.0.5"}
tokio = { version = "=0.2.22", features = ["full"]}
serde = { version = "1", features = ["derive"] }
log = "0.4"
thiserror = "1"
argh = "0.1.3"
confy = "0.4.0"
pretty_env_logger = "0.4"
bytes = "0.5.6"
flame = "0.2.2"
prost = "0.6"
pprof = { version = "0.3", features = ["flamegraph", "protobuf"] }
ctrlc = "=3.1"
jemallocator = "0.3"
