[package]
name = "rumqttd"
version = "0.12.0-alpha.3"
license = "Apache-2.0"
description = "rumqttd is a high performance MQTT broker written in Rust which is light weight and embeddable"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2021"
keywords = ["mqtt", "broker", "iot", "kafka", "nats"]
categories = ["network-programming"]
repository = "https://github.com/bytebeamio/rumqtt/"

[dependencies]
tokio = { version = "1.4.0", features = ["rt", "time", "net", "io-util", "macros"]}
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.66"
bytes = { version = "1", features = ["serde"] }
flume = "0.10.9"
slab = "0.4.3"
log = "0.4.14"
thiserror = "1.0.24"
tokio-util = { version = "0.7", features = ["codec"] }
tokio-rustls =  { version = "0.23.0", optional = true }
tokio-native-tls = { version = "0.3", optional = true }
rustls-pemfile = { version = "0.3.0", optional = true }
tokio-tungstenite = { version = "0.15.0", optional = true }
ws_stream_tungstenite = { version = "0.8", optional = true }
websocket-codec = { version = "0.5.1", optional = true }
rouille = "3.1.1"
x509-parser = {version= "0.9.2", optional = true}
futures-util = "0.3.16"
parking_lot = "0.11.2"
reqwest = { version = "0.11", features = ["json"] }
figment = { version = "0.10.5", features = ["toml", "env"] }
config = "0.13"
simplelog = "0.12.0"
structopt = "0.3.26"

[features]
default = ["use-rustls"]
use-rustls = ["tokio-rustls", "rustls-pemfile", "x509-parser"]
use-native-tls = ["tokio-native-tls", "x509-parser"]
websockets = ["tokio-tungstenite", "ws_stream_tungstenite", "websocket-codec"]

[dev-dependencies]
pretty_env_logger = "0.4.0"
mqttbytes = "0.6"
config = "0.13"
pretty_assertions = "1.3.0"

[target.'cfg(not(any(target_env = "msvc", target_env = "musl")))'.dependencies]
jemallocator = "0.3"

[build-dependencies]
vergen = "7.4.2"
