id = 0

# A commitlog read will pull full segment. Make sure that a segment isn't
# too big as async tcp writes readiness of one connection might affect tail
# latencies of other connection. Not a problem with preempting runtimes
[router]
id = 0
instant_ack = true
max_segment_size = 104857600
max_segment_count = 10
max_read_len = 10240
max_connections = 10010

[bridge.ba]
name = "bridge-ba"
addr = "localhost:1883"
qos = 0
sub_path = "#"
reconnection_delay = 5
ping_delay = 5
timeout_delay = 5
    [bridge.ba.connections]
    connection_timeout_ms = 60000
    max_client_id_len = 256
    throttle_delay_ms = 0
    max_payload_size = 20480
    max_inflight_count = 500
    max_inflight_size = 1024
    dynamic_filters = true

[bridge.bc]
name = "bridge-bc"
addr = "localhost:10883"
qos = 0
sub_path = "#"
reconnection_delay = 5
ping_delay = 5
timeout_delay = 5
    [bridge.bc.connections]
    connection_timeout_ms = 60000
    max_client_id_len = 256
    throttle_delay_ms = 0
    max_payload_size = 20480
    max_inflight_count = 500
    max_inflight_size = 1024
    dynamic_filters = true

# Configuration of server and connections that it accepts
[v4.1]
name = "v4-1"
listen = "0.0.0.0:9883"
next_connection_delay_ms = 1
    [v4.1.connections]
    connection_timeout_ms = 60000
    max_client_id_len = 256
    throttle_delay_ms = 0
    max_payload_size = 20480
    max_inflight_count = 500
    max_inflight_size = 1024
    dynamic_filters = true
 #   auth = { user1 = "p@ssw0rd", user2 = "password" }
 #      [v4.1.connections.auth]
 #      user1 = "p@ssw0rd"
 #      user2 = "password"

[v5.1]
name = "v5-1"
listen = "0.0.0.0:9884"
next_connection_delay_ms = 1
    [v5.1.connections]
    connection_timeout_ms = 60000
    max_client_id_len = 256
    throttle_delay_ms = 0
    max_payload_size = 20480
    max_inflight_count = 500
    max_inflight_size = 1024

[ws]

[console]
listen = "0.0.0.0:3031"
