[package]
name = "rumq-client"
version = "0.1.0"
authors = ["tekjar <kraviteza@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.15"
tokio = {version = "0.2.0-alpha.6", features = ["macros", "io"]}
tokio-rustls = "0.12.0-alpha.8"
tokio-io = "0.2.0-alpha.6"
futures-core = "0.3"
futures-sink = "0.3"
futures-util = { version = "=0.3", features = ["sink", "async-await"] }

rumq-core = {path = "../rumq-core", version = "0.1", features = ["tokio-traits"]}
log = "0.4"
async-stream = {git = "https://github.com/tokio-rs/async-stream"}

[dev-dependencies]
tokio-executor = {version = "0.2.0-alpha.6", features = ["current-thread"]}
pretty_env_logger = "0.3.1"
color-backtrace = "0.2.3"
serde = {version = "1", features = ["derive"]}
envy = "0.4"
jsonwebtoken = {git = "https://github.com/Keats/jsonwebtoken", branch = "next"}
futures-channel = "0.3"
futures-executor = "0.3"