[package]
name = "rumq-core"
version = "0.1.0-alpha.1"
description = "Serializes and deserializes mqtt byte stream"
license = "MIT"
repository = "https://github.com/tekjar/rumq"
authors = ["tekjar"]
edition = "2018"

[dependencies]
derive_more = "0.15"
tokio-byteorder = "0.2"
tokio = { version = "0.2", features = ["io-util"] }
async-trait = "0.1"
getset = "0.0.9"


[dev-dependencies]
tokio = {version = "0.2", features = ["full", "macros"]}
