[package]
name = "benchmarks"
version = "0.1.0"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1"
mqtt4bytes = { path = "../mqtt4bytes", version = "0.1"}
rumqttc = { path = "../rumqttc" }
rumqttlog = { path = "../rumqttlog" }
tokio = { version = "=0.2.19", features = ["full"] }
futures = { version = "0.3", features = ["compat"] }	
bytes = "0.5"
paho-mqtt = { git = "https://github.com/eclipse/paho.mqtt.rust" }
async-channel = "1"
pretty_env_logger = "0.4"
prost = "0.6"

pprof = { version = "0.3", features = ["flamegraph", "protobuf"] }

[[bin]]
name = "rumqttasync"
path = "rumqttasync.rs"

[[bin]]
name = "rumqttsync"
path = "rumqttsync.rs"

[[bin]]
name = "routernxn"
path = "routernxn.rs"

[[bin]]
name = "pahosync"
path = "pahosync.rs"

[[bin]]
name = "pahoasync"
path = "pahoasync.rs"
