[package]
name = "benchmarks"
version = "0.1.0"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = { path = "../rumqttc" }
tokio = { version = "0.2", features = ["full"]}
async-channel = "1"
pretty_env_logger = "0.4"
prost = "0.6"
pprof = { version = "0.3", features = ["flamegraph", "protobuf"] }

[[bin]]
name = "rumqttasync"
path = "rumqttasync.rs"

[[bin]]
name = "rumqttsync"
path = "rumqttsync.rs"
