on:
  push:
    branches:
      - master

name: master

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
  GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}

jobs:
  test:
    name: source build and test
    runs-on: [self-hosted, linux, X64, rumqtt]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features

  deploy:
    name: source build, docker build and deploy
    runs-on: [self-hosted, linux, X64, rumqtt]

    steps:
    - name: githun actions checkout
      uses: actions/checkout@v2

    # Cargo setup and build
    - name: cargo setup and build
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    # Setup gcloud CLI
    - name: gcp setup
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - name: docker google cloud registry auth
      run: |-
        gcloud --quiet auth configure-docker

    # Copy rumqttd and config files 
    - name: prepare config and binary
      run: |-
        cp -r target/release/rumqttd stage/
        cp -r rumqttd/config stage/

    # Build the Docker image
    - name: docker build
      run: |-
        working-directory: docker
        docker build --tag "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA" .

    # Push the Docker image to Google Container Registry
    - name: docker image publish
      run: |-
        docker push "asia.gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA"

    # Deploy the container
    - name: deploy
      run: |-
        gcloud compute instances update-container "$GCE_INSTANCE" \
          --zone "$GCE_INSTANCE_ZONE" \
          --container-image "asia.gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA"
