[package]
name = "rumqttc"
version = "0.3.0"
description = "An efficient and robust mqtt client for your connected devices"
license = "Apache-2.0"
repository = "https://github.com/bytebeamio/rumqtt"
authors = ["tekjar"]
edition = "2018"
keywords = ["mqtt", "iot", "coap", "http"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
bytes = "1.0"
webpki = "0.21"
tokio-rustls = "0.22"
async-tungstenite = { version = "0.11.0", default-features = false, features = ["tokio-rustls"] }
ws_stream_tungstenite = { version = "0.4.0", default-features = false, features = ["tokio_io"] }
mqttbytes = { path = "../mqttbytes", version = "0.1" }
pollster = "0.2"
async-channel = "1.5"
log = "0.4"
thiserror = "1.0.21"
http = "^0.2"

[dev-dependencies]
pretty_env_logger = "0.4"
color-backtrace = "0.4"
crossbeam-channel = "0.5"
serde = {version = "1", features = ["derive"]}
envy = "0.4"
jsonwebtoken = "7"
tokio = { version = "1.0", features = ["full", "macros"] }
matches = "0.1.8"
rustls = "0.19"
rustls-native-certs = "0.5.0"
